### Задание 1
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [1]:
import pandas as pd

In [2]:
%%time

ratings = pd.read_csv('ml-25m/ratings.csv')
movies = pd.read_csv('ml-25m/movies.csv')
ratings[ratings['rating'] == 5.0] \
    .merge(movies[['movieId', 'title']], on='movieId')['title'] \
    .value_counts()

CPU times: user 6.47 s, sys: 2.07 s, total: 8.54 s
Wall time: 9.36 s

Shawshank Redemption, The (1994)             39553
Pulp Fiction (1994)                          32169
Forrest Gump (1994)                          25918
Star Wars: Episode IV - A New Hope (1977)    25804
Matrix, The (1999)                           25482
                                             ...
Chop Suey (2001)                                 1
Hickok (2017)                                    1
Juno and the Paycock (1930)                      1
House of Purgatory (2016)                        1
Shaitan (2011)                                   1
Name: title, Length: 27112, dtype: int64

#### Вывод
Больше всего оценок 5.0 поставили фильму Shawshank Redemption, The (1994) (Побег из Шоушенка)
#### Второй вывод
Меньше чем за 10 секунд загрузить два файла на 800Мб и смержить их - для меня это фантастика

### Задание 2
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [3]:
power = pd.read_csv('power.csv')
power[
    (power['country'].isin(['Latvia', 'Lithuania', 'Estonia']))
    & (power['category'].isin([4, 12, 21]))
    & (power['year'].isin(range(2005, 2011)))
    & (power['quantity'] > 0)
    ]['quantity'] \
    .sum()

240580.0

### Задание 3
Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.
Примеры страниц (необязательно брать именно эти):

https://fortrader.org/quotes

https://www.finanz.ru/valyuty/v-realnom-vremeni

In [4]:
pd.read_html('https://www.championat.com/football/_england/tournament/2995/table/')[0]

,№,Команда,Игры,В,Н,П,Мячи,Очки,% очков,Форма
0,1,Ливерпуль,31,28,2,1,70-21,86,925,NaN
1,2,Манчестер Сити,31,20,3,8,77-33,63,677,NaN
2,3,Лестер Сити,31,16,7,8,59-29,55,591,NaN
3,4,Челси,31,16,6,9,55-41,54,581,NaN
4,5,Манчестер Юнайтед,31,13,10,8,48-31,49,527,NaN
5,6,Вулверхэмптон,31,12,13,6,44-34,49,527,NaN
6,7,Тоттенхэм Хотспур,31,12,9,10,50-41,45,484,NaN
7,8,Шеффилд Юнайтед,31,11,11,9,30-31,44,473,NaN
8,9,Арсенал,31,10,13,8,43-41,43,462,NaN
9,10,Кристал Пэлас,31,11,9,11,28-36,42,452,NaN
10,11,Бёрнли,31,12,6,13,35-45,42,452,NaN
11,12,Эвертон,31,11,8,12,38-46,41,441,NaN
12,13,Ньюкасл Юнайтед,31,10,9,12,29-42,39,419,NaN
13,14,Саутгемптон,31,11,4,16,38-54,37,398,NaN
14,15,Брайтон энд Хоув Альбион,31,7,12,12,34-41,33,355,NaN
15,16,Уотфорд,31,6,10,15,28-46,28,301,NaN
16,17,Вест Хэм Юнайтед,31,7,6,18,35-54,27,290,NaN
17,18,Борнмут,31,7,6,18,29-50,27,290,NaN
18,19,Астон Вилла,31,7,6,18,36-59,27,290,NaN
19,20,Норвич Сити,31,5,6,20,25-56,21,226,NaN